---
title: "Group 3 Final Project"
author: "Natalie Collins, Peter Kessinger, MacKenzie Hennes, & Audrey Dickinson"
date: "12/16/2020"
output:
  flexdashboard::flex_dashboard: default
---

  
```{r}
library(tidyverse)
library(flexdashboard)
library(lubridate)
library(shiny)
library(jsonlite)
library(maptools)
library(leaflet)
library(plotly)
library(DT)
library(ggthemes)
library(viridis)
library(crosstalk)

outbreak_list <- read.csv(file = "larimer_covid_outbreaks.csv")
outbreak_list <- outbreak_list %>%
  select(Facility, Status, Type, Date.Outbreak.Determined, Staff.Cases.Confirmed) %>% 
  mutate(Staff.Cases.Confirmed = ifelse(!is.na(Staff.Cases.Confirmed), Staff.Cases.Confirmed, 0)) %>% 
  rename(Location = Facility, Date = Date.Outbreak.Determined,
         Cases = Staff.Cases.Confirmed)
```


Column {.sidebar data-width=250}
-------------------------------------
### Larimer County Outbreaks

Use this tab to identify Covid-19 outbreaks in Larimer County. The data is sourced from the Larimer County Department of Health and Environment.

An active outbreak is defined as two or more cases within a facility or a workplace. The identification of outbreaks and the subsequent contact tracing is an important measure in limiting the spread of Covid-19 in our communities. 

The outbreak graph by month is static and will not reflect changes by industry. The outbreak barplot however will reflect the changes based on the selected industry. To switch between the two views, use the tabs at the top.

The value boxes in the bottom middle reflect the number of confirmed cases and deaths in Larimer County. We chose not to include those identified as probable cases.

Filter by status, type, or date to explore outbreaks in our community. 

Use the below drop down menu to limit outbreaks by industry.

```{r}
Larimer_shared1 <- SharedData$new(outbreak_list, ~Type, group = "Choose Industry")
Larimer_shared2 <- SharedData$new(outbreak_list, ~Type, group = "Choose Industry")

filter_select("Type", "Choose Industry:", Larimer_shared1, ~Type)


```

Row {data-height=600}
-------------------------------------
### Outbreak Table

```{r}
datatable(Larimer_shared1, extensions = "Scroller", style="bootstrap", class="compact", width="100%", options=list(deferRender=TRUE, scrollY=300, scroller=TRUE))
```


### Confirmed Cases

```{r}
case_data <- read_csv("larimer_covid_cases.csv") %>% 
  group_by(Type) %>% 
  count() %>% 
  filter(Type == "Confirmed")

valueBox(case_data$n ,caption = "Confirmed Cases", icon = "fa-group")
```

### Confirmed Deaths
```{r}
death_data <- read_csv("larimer_covid_deaths.csv")

death_data <- death_data %>% 
  group_by(case_status) %>% 
  count() %>% 
  filter(case_status == "Confirmed")

valueBox(death_data$n ,caption = "Confirmed Deaths", icon = "fa-medkit")

```

Column {data-width=400, .tabset}
-------------------------------------
  
### Covid-19 Outbreaks by Month

```{r}
outbreak_dates <- outbreak_list %>% 
  mutate(Date = mdy(Date)) %>%  
  mutate(month(Date, label = TRUE)) %>% 
  rename(start_month = `month(Date, label = TRUE)`)

outbreak_graph <- outbreak_dates %>% 
  ggplot(aes(x = start_month)) +
  geom_bar() +
  theme_few()+
  labs(x = "Month Outbreak Started", y = "Number of Outbreaks", 
       title = "Community Covid-19 Outbreaks by Month")
  

outbreak_graph
```

### Outbreak Barplot

```{r}
plot_ly(Larimer_shared1, x = ~Type, y = ~Cases, color = ~Status) %>%
  group_by(Type) %>% 
  add_bars()
```


